### ISSUE TITLE
modelSum API says forbidden

### ISSUE THREAD

**Issue by tdhock** [PeakLearner/PeakLearner#110]
R code I used,
```r
modelSum.csv <- tempfile()
modelSum.url <- "https://peaklearner.rc.nau.edu/Public/H3K4me3_TDH_ENCODE/aorta_ENCFF115HTK/modelSum?ref=chr1&start=143644525"
while(1){
  download.file( modelSum.url, modelSum.csv,   quiet=TRUE, headers=c("accept"="text/csv"))
}
```
If I only do this once, it will randomly succeed or fail. Since I do it in a while(1) loop, it eventually fails (403 forbidden). I expected it should always succeed. @deltarod can you please investigate/fix?

**Comment by deltarod** [comment]
I am unable to reproduce this. 

The only issues I can see in the logs were just a malformed URL.

Here are the only errors I see:

`
INFO:     10.0.2.100:34230 - "GET /Public/H3K4me3_TDH_ENCODE//thyroid_Input_ENCFF995SFR/modelSum?ref=chrY&start=58967656 HTTP/1.1" 404 Not Found

INFO:     127.0.0.1:54398 - "GET /runJobSpawn HTTP/1.1" 200 OK

INFO:     127.0.0.1:54400 - "GET /runJobSpawn HTTP/1.1" 200 OK

INFO:     10.0.2.100:34236 - "GET /Public/H3K4me3_TDH_ENCODE//aorta_ENCFF974KVN/modelSum?ref=chr10&start=60000 HTTP/1.1" 404 Not Found

`
