### ISSUE TITLE
display of who is logged in?

### ISSUE THREAD

**Issue by tdhock** [PeakLearner/PeakLearner#40]
Hi @deltarod I see my user id on the peaklearner home page, but not on the genome browser page. How can a user tell if/who is logged in, on the genome browser page?
can you display the user ID who last modified below or next to each label?

**Comment by tdhock** [comment]
hi @deltarod this is still an issue, can you please investigate and fix?

**Comment by deltarod** [comment]
![img](https://user-images.githubusercontent.com/12278781/129812430-786ebcaa-368b-4aae-baa8-03a5d9f013c7.png)

not very pretty but it works

**Comment by tdhock** [comment]
perfect
