### ISSUE TITLE
user-centric label counts?

### ISSUE THREAD

**Issue by tdhock** [PeakLearner/PeakLearner#42]
hey @deltarod can you please implement web page that shows, for the current user, counts of how many labels have been created?
- overview page: table with row for each hub, column for # labels, # tracks

**Comment by tdhock** [comment]
links for each hub to label count details page #43

**Comment by deltarod** [comment]
Would this be a way to query any users labels, or the current, logged in user to see the labels in which they have created?

**Comment by tdhock** [comment]
would be nice to have info for both (1) current user and (2) other users which can access the hubs that this user can see.

**Comment by deltarod** [comment]
So for each hub, have a column with num labels of current user, number of tracks in hub, and total number of labels?

**Comment by tdhock** [comment]
that would be a good start yes.

**Comment by deltarod** [comment]
How does this look?

![image](https://user-images.githubusercontent.com/12278781/135166894-7b6a71d0-d8e5-4630-b5a7-2de6897bdf45.png)

**Comment by tdhock** [comment]
awesome thanks! looks really clean, I like it!

**Comment by tdhock** [comment]
what is the URL for that new page?

**Comment by deltarod** [comment]
Sign in, then either go to https://peaklearner.rc.nau.edu/profile or click your email at the top right, then click profile.

**Comment by tdhock** [comment]
@brookesebranek this is how you can see your total label counts.
