### ISSUE TITLE
test for user id of label before and after logging in

### ISSUE THREAD

**Issue by tdhock** [PeakLearner/PeakLearner#44]
hi @deltarod I am observing labels in the database with user id "None" even after I have logged in.
Can you please write a test that checks
- for a label with user ID "anonymous" or "not logged in" before having logged in
- if I log in using tdhock5@gmail.com, then add a label, I would expect that lastModifiedBy="tdhock5@gmail.com" for that label

**Comment by tdhock** [comment]
if you have to prioritize any of the new issues I filed today, can you make this one top priority, because Jack's project depends on storing different values of the user ID.

**Comment by tdhock** [comment]
hi again @deltarod this is still an issue.
This is a critical feature for several projects. Can you please fix? I need to be able to download the labels and know what user created each label.

**Comment by deltarod** [comment]
I'm not sure how to test "Logging in", I've tried a few different ways with Selenium and nothing seems to work quite right. The values should be in the track labels route once I update the server

**Comment by tdhock** [comment]
for testing https://sqa.stackexchange.com/questions/42307/trying-to-login-to-gmail-with-selenium-but-this-browser-or-app-may-not-be-secur says that you should use oauth2 api https://developers.google.com/identity/protocols/oauth2/native-app 
I did web search for "how to test logging into google account web app selenium"
