### ISSUE TITLE
remove peaks below data

### ISSUE THREAD

**Issue by tdhock** [PeakLearner/PeakLearner#48]
hi @deltarod I observe red peak bars plotted below the data, see screenshot. can you please investigate / fix?
![peaks-below-data](https://user-images.githubusercontent.com/932850/120703617-88370880-c483-11eb-858b-56c541c36e6b.png)

**Comment by tdhock** [comment]
i believe this is for prediction type=None so probably PeakSegDisk models

**Comment by deltarod** [comment]
For this specific fix, the height value used to draw the data was being taken from the bottom of the track block dom node instead of the data dom node. The difference in height here was about 18-20 pixels. 

jbrowse/jbrowse/plugins/PeakLearnerBackend/js/View/Track/Model.js

**Comment by tdhock** [comment]
thanks!
