### ISSUE TITLE
missing peak predictions

### ISSUE THREAD

**Issue by tdhock** [PeakLearner/PeakLearner#49]
hi @deltarod I observed an area with some red peak bars missing even after adding start / end labels. can you please investigate, create a test case that fails with the current code, then fix?
![some-missing-peaks](https://user-images.githubusercontent.com/932850/120704288-69854180-c484-11eb-95ad-bf9eef023227.png)

**Comment by tdhock** [comment]
i believe this is for prediction type=None so probably PeakSegDisk models

**Comment by deltarod** [comment]
FLOPART is enabled by default and will display when there is no PeakSegDisk model available. 

The last improvement which can be made in this area is learning a penalty for the alt models like (F)LOPART. I struggle to see how a system like that could be designed when I can generate practically infinite data points at different zoom levels/locations on a single data track, let alone gathering enough data to be able to generalize it. There are a ton of ways to look at this problem and I don't feel like I have a good enough understanding to implement something like this.
