### ISSUE TITLE
line breaks in json please

### ISSUE THREAD

**Issue by tdhock** [PeakLearner/PeakLearner#57]
hi @deltarod can you please put line breaks in the json output? and change default to csv? csv is preferable. 
or just remove the json output?
I got json by accident, and it did not have any line breaks, which made it impossible to parse. this is data from:
https://peaklearner.rc.nau.edu/Public/H3K4me3_TDH_ENCODE/labels/

**Comment by deltarod** [comment]
In order to get a csv output you need to use the header 'Accept' with a value of 'txt/csv'.

**Comment by deltarod** [comment]
Json parsers should be able to handle it without line breaks. For everything else, there is now csv output which should work.

**Comment by tdhock** [comment]
I realize that json parsers should be handle it ok, but shouldn't it be easy to add a line break after every }, in that json file?
it still would be nice to have this feature, for the following use case
1. user downloads labels API endpoint to file.csv (without specifying accept=txt/csv) so actually data is json
2. user tries to read that file using CSV parser
3. user waits for a long time before realizing that it is actually not a CSV file
 (would be better for 3. to fail gracefully/early)

**Comment by deltarod** [comment]
Do you have any code I can use to try and replicate this behavior?

**Comment by tdhock** [comment]
```r
labels.csv <- tempfile()
download.file("https://peaklearner.rc.nau.edu/Public/H3K4me3_TDH_ENCODE/labels", labels.csv)
labels.dt <- data.table::fread(labels.csv)
```

**Comment by deltarod** [comment]
Following https://stackoverflow.com/a/69221989/14396857

it takes about the same amount of time regardless of whether or not I use the pretty json'd version or not. When testing endpoints using the docs page it provides information on the headers to pass so I'm going to go ahead and close this now.
