### ISSUE TITLE
Check over of the job spawning system

### ISSUE THREAD

**Issue by deltarod** [PeakLearner/PeakLearner#65]
@tdhock Could you please look over the job spawner? I merged #63 as it was holding me up.

The main chunk of code is all lines below this point: https://github.com/PeakLearner/PeakLearner/blob/ec6e492cfce0554e75797fe3942041a5c4c20d06/core/Jobs/Jobs.py#L668

**Comment by tdhock** [comment]
sure, but can you please clarify what part of that code you want me to look over? What is your intent? What are your questions?

**Comment by deltarod** [comment]
Honestly, I'm still not quite happy with this. It blocks for quite a while because I am checking every job added to see if it already exists. Data intake is also slowing down the whole server so I am beginning to investigate breaking that off into more of a "microservices" approach. The microservices approach should make future scaling a lot easier as well.

**Comment by tdhock** [comment]
about "I am checking every job added to see if it already exists" you should be using the database to handle that efficiently, what are you doing now?

**Comment by deltarod** [comment]
Currently it is looping through all the jobs to see if there are any which match it due to some conditions. I hadn't really designed this with the idea of spawning 100 jobs at a time.

**Comment by tdhock** [comment]
when you do "looping through all the jobs" does that mean a for loop over all key/value entries in a data base? If this is a speed problem then please refactor for efficiency. BDB should offer some way of doing this.
