### ISSUE TITLE
Peaks displayed in nopeaks label

### ISSUE THREAD

**Issue by tdhock** [PeakLearner/PeakLearner#72]
![image](https://user-images.githubusercontent.com/932850/129622330-9c1ff6cf-0376-4902-a934-20566e86a37e.png)
@deltarod please investigate and fix

**Comment by deltarod** [comment]
I think I might have an idea on why it is doing this. The model currently being displayed is a predicted model and for some reason the summary didn't update after adding the labels.

**Comment by tdhock** [comment]
you don't have a test case for this (no peak shown in nopeaks label) yet?

**Comment by deltarod** [comment]
No, this interaction is pretty new due to how prediction models are stored.

**Comment by tdhock** [comment]
please add a test case
