### ISSUE TITLE
missing peakstart labels

### ISSUE THREAD

**Issue by tdhock** [PeakLearner/PeakLearner#73]
I created some peakstart labels in all tracks, then scrolled away, then scrolled back, and now they are gone, but only in a few of the tracks. can you please investigate and fix @deltarod ?
![image](https://user-images.githubusercontent.com/932850/129622678-685f02c1-6be9-4e4e-b640-2ce00142c113.png)

**Comment by deltarod** [comment]
I don't quite remember what the issue with this was, but I think some of the changes which have been made since this issue popped up have solved it.
