### ISSUE TITLE
use R-tree for storing spatial data such as labels

### ISSUE THREAD

**Issue by tdhock** [PeakLearner/PeakLearner#82]

**Comment by tdhock** [comment]
@deltarod  this is supported by sqlite https://www.sqlite.org/rtree.html and berkeley db, https://docs.oracle.com/cd/E17076_02/html/installation/build_unix_sql.html#idp50563608

**Comment by deltarod** [comment]
There is 0 information on how to implement this using bsddb3/berkeleydb python packages. There is hardly any information on how to utilize it using the base implementation for berkeleydb other than that page. I don't think this is particularly feasible

**Comment by tdhock** [comment]
we can just use bigWig instead
