### ISSUE TITLE
zoom in to see model shown in an area where peaks should be shown

### ISSUE THREAD

**Issue by tdhock** [PeakLearner/PeakLearner#89]
![image](https://user-images.githubusercontent.com/932850/134558417-3f138dba-438f-42c9-8962-3fd89a77e785.png)
in the screenshot above, for hub=H3K36me3_TDH_other, we see some peaks in the data, but no peak predictions, why?
@deltarod can you please investigate and fix?

**Comment by deltarod** [comment]
This is caused by the scale. If you zoomed in one more time it would have shown. The further zoomed out, either the summary data will become less accurate (Current case) or I could make it use more data points as well.

**Comment by tdhock** [comment]
I don't understand. Can you clarify? By "summary data" do you mean the output of bigWigSummary? How does that become less accurate?
What do you mean by "use more data points"? 
Different data types will have relevant peaks at different scales (here very zoomed out, others very zoomed in), and PeakLearner should show peak predictions at whatever scale is relevant for that data type (as indicated by the labels and peak predictions).

**Comment by deltarod** [comment]
Now that you say that I don't remember quite why I implemented it that way specifically. I've gone ahead and removed that line. for the data part, I'm also looking at #75 and just included a little too much information.
