### ISSUE TITLE
remove space between tracks?

### ISSUE THREAD

**Issue by tdhock** [PeakLearner/PeakLearner#90]
![image](https://user-images.githubusercontent.com/932850/134558887-629bba51-6e21-4653-8148-adb96a75780f.png)
I resized the quantitative tracks to 15 pixels using the new feature #88 (thanks for implementing!)
however now it seems there is a bunch of wasted/white space between tracks.
@deltarod can you please investigate? is that configurable? can that be reduced so we can see more data tracks on screen at once?

**Comment by deltarod** [comment]
I'm not sure. @cmdcolin is this feasible?

**Comment by cmdcolin** [comment]
can do with https://github.com/bhofmei/jbplugin-hierarchicalcheckbox

**Comment by cmdcolin** [comment]
can change view->trackPadding global option https://jbrowse.org/docs/global_options.html
e.g.

view.trackPadding=0

in jbrowse.conf

**Comment by deltarod** [comment]
Nice thanks!

**Comment by deltarod** [comment]
![image](https://user-images.githubusercontent.com/12278781/134733410-1b23f95a-b9be-4a70-bf88-108f54113ff2.png)

Packed in there a little more, this is with a height of 50

**Comment by tdhock** [comment]
that looks better thanks
