### ISSUE TITLE
show/hide all tracks with a given cell type with one click?

### ISSUE THREAD

**Issue by tdhock** [PeakLearner/PeakLearner#91]
![image](https://user-images.githubusercontent.com/932850/134559598-9be2d047-c88d-4e4f-8868-8636ed01014d.png)
currently to show/hide a track we need to click a box next to each track on the left.
Sometimes it would be useful if we could show/hide all tracks of a given type with one click (for example tcell has 10+ samples above, would be nice to hide/show them all with one mouse click rather than 10+).
@deltarod is it possible to add a check box next to the track group, and have that control all of the tracks in that group?

**Comment by deltarod** [comment]
@cmdcolin is this something which is doable or is already implemented in jb2?

**Comment by cmdcolin** [comment]
can do with https://github.com/bhofmei/jbplugin-hierarchicalcheckbox

**Comment by deltarod** [comment]
![image](https://user-images.githubusercontent.com/12278781/134738907-259d21e6-965f-4c43-bb26-02879a9f51a4.png)

Awesome, that worked but I also added the ability to not toggle tracks if the category is hidden.

**Comment by tdhock** [comment]
great thanks
